From VM Thu Feb 22 16:05:17 2001
Return-Path: <python-list-admin@python.org>
Delivered-To: zzzzz@wwww.org
Received: from digicool.com (host15.digitalcreations.d.subnet.rcn.com [208.59.6.15])
	by mail.wwww.org (Postfix) with ESMTP id AD081D37AC
	for <zzzzz@wwww.org>; Thu, 22 Feb 2001 04:54:37 -0500 (EST)
Received: from <python-list-admin@python.org>
  by digicool.com (CommuniGate Pro RULES 3.3.2)
  with RULES id 1498944; Thu, 22 Feb 2001 04:56:22 -0500
Received: from ns2.digicool.com ([216.164.72.2] verified)
  by digicool.com (CommuniGate Pro SMTP 3.3.2)
  with ESMTP id 1498943 for zzzzz@mail.digicool.com; Thu, 22 Feb 2001 04:56:22 -0500
Received: from mail.python.org (mail.python.org [63.102.49.29])
	by ns2.digicool.com (8.9.3/8.9.3) with ESMTP id EAA15538
	for <zzzzz@digicool.com>; Thu, 22 Feb 2001 04:54:14 -0500
Received: from localhost.localdomain ([127.0.0.1] helo=mail.python.org)
	by mail.python.org with esmtp (Exim 3.21 #1)
	id 14VsRz-0002Md-00
	for zzzzz@digicool.com; Thu, 22 Feb 2001 04:54:15 -0500
Received: from [204.68.24.95] (helo=nm195.netaddress.usa.net)
	by mail.python.org with smtp (Exim 3.21 #1)
	id 14VsRh-0002K2-00
	for python-list-admin@python.org; Thu, 22 Feb 2001 04:53:57 -0500
Received: (qmail 1169 invoked by uid 0); 22 Feb 2001 09:51:46 -0000
Message-ID: <20010222095146.1166.qmail@nm195.netaddress.usa.net>
Precedence: bulk
List-Help: <mailto:python-list-request@python.org?subject=help>
List-Post: <mailto:python-list@python.org>
List-Subscribe: <http://mail.python.org/mailman/listinfo/python-list>,
	<mailto:python-list-request@python.org?subject=subscribe>
List-Id: General discussion list for the Python programming language <python-list.python.org>
List-Unsubscribe: <http://mail.python.org/mailman/listinfo/python-list>,
	<mailto:python-list-request@python.org?subject=unsubscribe>
List-Archive: <http://mail.python.org/pipermail/python-list/>
From: MAILER-DAEMON@usa.net
Sender: python-list-owner@python.org
To: python-list-admin@python.org
Subject: Processing Error
Date: 22 Feb 2001 09:51:46 -0000
X-Autogenerated: Mirror
X-Mirrored-by: <python-list-admin@python.org>
X-BeenThere: python-list@python.org
X-Mailman-Version: 2.0.1 (101270)

Intended recipient: chris.ggggmmmm@usa.net

The following mail has been returned because it encountered an error
while being processed.  Please try to resend this message.

A notice of this error has been reported to the POSTMASTER at USA.NET
which will attempt to contact the intended recipient.

--------RETURNED MAIL FOLLOWS--------
Received: from mail.python.org [63.102.49.29] by nm195 via mtad (34FM.0700.12.01) 
	with ESMTP id 167FBVJzI0889M19; Thu, 22 Feb 2001 09:51:43 GMT
Received: from localhost.localdomain ([127.0.0.1] helo=mail.python.org)
	by mail.python.org with esmtp (Exim 3.21 #1)
	id 14Vs49-0000n4-00; Thu, 22 Feb 2001 04:29:37 -0500
Path: news.baymountain.net!uunet!ash.uu.net!npeer.kpnqwest.net!news.tele.dk!130.133.1.3!fu-berlin.de!uni-berlin.de!adsl-138-89-39-3.nnj.adsl.bellatlantic.NET!not-for-mail
From: ccccc@meezon.com (Ccccc Mmmmm)
Newsgroups: comp.lang.python
Subject: Re: import statement is case sensitive
Lines: 28
Message-ID: <3a947ac4.802440@News.CIS.DFN.DE>
References: <3a943bea.525315589@News.CIS.DFN.DE> <t98i9hsgjkov26@corp.supernews.com>
NNTP-Posting-Host: adsl-138-89-39-3.nnj.adsl.bellatlantic.net (138.89.39.3)
X-Trace: fu-berlin.de 982810722 24108160 138.89.39.3 (16 [57226])
X-Newsreader: Forte Free Agent 1.1/32.230
Xref: news.baymountain.net comp.lang.python:89820
To: python-list@python.org
Sender: python-list-admin@python.org
Errors-To: python-list-admin@python.org
X-BeenThere: python-list@python.org
X-Mailman-Version: 2.0.1 (101270)
Precedence: bulk
List-Help: <mailto:python-list-request@python.org?subject=help>
List-Post: <mailto:python-list@python.org>
List-Subscribe: <http://mail.python.org/mailman/listinfo/python-list>,
	<mailto:python-list-request@python.org?subject=subscribe>
List-Id: General discussion list for the Python programming language <python-list.python.org>
List-Unsubscribe: <http://mail.python.org/mailman/listinfo/python-list>,
	<mailto:python-list-request@python.org?subject=unsubscribe>
List-Archive: <http://mail.python.org/pipermail/python-list/>
Date: Thu, 22 Feb 2001 02:58:29 GMT

"Lyle" <lllll@rrrrgggg.com> wrote:

>> Also what is the purpose of even having it case sensitive. I've yet to
>> see a file system that has case sensitive filenames....
>
>There is an operating system called "Unix" that has case-sensitive file
>names. There is a slight chance that others on this newsgroup have also
>heard of this obscure operating system.
>

Well given the fact that Linux and Windows is beating it to death I
can see why Unix is becoming obscure :)

Actually I would consider this a shortcoming of Unix. Shipping a
product that depends on the directory names and files being in the
right case must cause all sorts of headaches.

I am trying to run an an application under Windows and now I have to
worry if my directory name is in the correct case. I use PythonWin (a
fantastic product) to run and test it. There is no option for telling
it to ignore the case of the import filenames that I could see.

And renaming directories and files is not an easy option.. But anyway,
this is should automatically be handled in Python depending on the OS.


Why would asnyone make the same filenames with different cases? Is
there a good use?
-- 
http://mail.python.org/mailman/listinfo/python-list
---------END OF RETURNED MAIL--------


